// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/merge.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Image struct {
	Sha256               string   `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_030f259fb68ccd7d, []int{0}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetSha256() string {
	if m != nil {
		return m.Sha256
	}
	return ""
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_030f259fb68ccd7d, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MergeRequest struct {
	Image                *Image   `protobuf:"bytes,1,opt,name=Image,proto3" json:"Image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MergeRequest) Reset()         { *m = MergeRequest{} }
func (m *MergeRequest) String() string { return proto.CompactTextString(m) }
func (*MergeRequest) ProtoMessage()    {}
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030f259fb68ccd7d, []int{2}
}

func (m *MergeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeRequest.Unmarshal(m, b)
}
func (m *MergeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeRequest.Marshal(b, m, deterministic)
}
func (m *MergeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeRequest.Merge(m, src)
}
func (m *MergeRequest) XXX_Size() int {
	return xxx_messageInfo_MergeRequest.Size(m)
}
func (m *MergeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MergeRequest proto.InternalMessageInfo

func (m *MergeRequest) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type MergeResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MergeResponse) Reset()         { *m = MergeResponse{} }
func (m *MergeResponse) String() string { return proto.CompactTextString(m) }
func (*MergeResponse) ProtoMessage()    {}
func (*MergeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030f259fb68ccd7d, []int{3}
}

func (m *MergeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeResponse.Unmarshal(m, b)
}
func (m *MergeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeResponse.Marshal(b, m, deterministic)
}
func (m *MergeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeResponse.Merge(m, src)
}
func (m *MergeResponse) XXX_Size() int {
	return xxx_messageInfo_MergeResponse.Size(m)
}
func (m *MergeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MergeResponse proto.InternalMessageInfo

func (m *MergeResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Image)(nil), "proto.Image")
	proto.RegisterType((*Error)(nil), "proto.Error")
	proto.RegisterType((*MergeRequest)(nil), "proto.MergeRequest")
	proto.RegisterType((*MergeResponse)(nil), "proto.MergeResponse")
}

func init() { proto.RegisterFile("proto/merge.proto", fileDescriptor_030f259fb68ccd7d) }

var fileDescriptor_030f259fb68ccd7d = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x4a, 0x4f, 0xd5, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x94, 0x92, 0x3c,
	0x17, 0xab, 0x67, 0x6e, 0x62, 0x7a, 0xaa, 0x90, 0x18, 0x17, 0x5b, 0x71, 0x46, 0xa2, 0x91, 0xa9,
	0x99, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x94, 0xa7, 0x64, 0xca, 0xc5, 0xea, 0x5a, 0x54,
	0x94, 0x5f, 0x24, 0x24, 0xc4, 0xc5, 0xe2, 0x9c, 0x9f, 0x92, 0x0a, 0x95, 0x06, 0xb3, 0x85, 0x24,
	0xb8, 0xd8, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x98, 0xc0, 0xc2, 0x30, 0xae, 0x92,
	0x11, 0x17, 0x8f, 0x2f, 0xc8, 0xb6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x25, 0xa8,
	0x3d, 0x60, 0xed, 0xdc, 0x46, 0x3c, 0x10, 0x57, 0xe8, 0x81, 0xc5, 0x82, 0x20, 0x52, 0x4a, 0xc6,
	0x5c, 0xbc, 0x50, 0x3d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x20, 0x4d, 0x60, 0xbb, 0xd1, 0x34,
	0x81, 0xc5, 0x82, 0x20, 0x52, 0x46, 0x76, 0x5c, 0x6c, 0x60, 0x4d, 0x45, 0x42, 0x26, 0x5c, 0xac,
	0x60, 0x96, 0x90, 0x30, 0x54, 0x1d, 0xb2, 0x03, 0xa4, 0x44, 0x50, 0x05, 0x21, 0x36, 0x28, 0x31,
	0x38, 0xb1, 0x47, 0xb1, 0xea, 0x59, 0x17, 0x15, 0x24, 0x27, 0xb1, 0x81, 0xe5, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xde, 0x08, 0x4a, 0x06, 0x2c, 0x01, 0x00, 0x00,
}
